/* autogenerated by Processing revision 1292 on 2025-08-08 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import fisica.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class rocket2 extends PApplet {

//A 2D game designed by Edward Collins.
//In each level the player must use the arrow keys to navigate a rocket to land on its landing pad.
//In order to compile and run, this program requires access to the Fisica library by Richard Marxer.



Engine engine;
Game game;
FWorld world;
float scale;
PFont myFont ;

public void settings() {//set screen size so that aspect ratio = 16 : 9
  int maxW = displayWidth;
  int maxH = displayHeight;
  if (abs( maxH * 16 / 9 - maxW) < 3) fullScreen();
  else if ( maxH * 16 / 9 - maxW < 0) size(maxH * 16 / 9, maxH);
  else size(maxW, maxW * 9 / 16);
}

public void setup() {
  scale = width / 1920.0f;
  Fisica.init(this);
  engine = new Engine();
}

public void draw() {
  scale(scale); //rest of the program assumes dimensions of (1920, 1080)
  engine.control();
}

//events called by fisica
public void contactStarted(FContact c) {
  game.contactStarted(c);
}

public void contactPersisted(FContact c) {
  game.contactPersisted(c);
}

public void contactEnded(FContact c) {
  game.contactEnded(c);
}

public void mousePressed() {
  engine.mousePressed();
}

public void keyPressed() {
  engine.keyPressed();
}

public void keyReleased() {
  engine.keyReleased();
}

public void displayStar(float x, float y, float r) {
  int z = PApplet.parseInt(r*.3f);
  for (float i = -PI/10; i < 5; i += TAU/5) {
    triangle(x + r*cos(i), y + r*sin(i), x + z*cos(i + PI/2), y + z*sin(i + PI/2),
      x + z*cos(i - PI/2), y + z*sin(i - PI/2));
  }
}
//class that controls an alien

class Alien extends Bonus {

  FPoly a;
  int s = 1920/45;
  int timer = 0;

//r = x_speed , value = bullet_force/10000 , value2 = fire frequency.
  Alien(float x, float y, float r, float value, float value2) {
    super(x, y, r, "alien", value, value2);
    a = new FPoly();
    a(.4f, -.6f);
    a(.6f, -.2f);
    a(1, 0);
    a(.8f, .2f);
    a(.6f, .3f);
    a(0, .4f);
    a(-.6f, .3f);
    a(-.8f, .2f);
    a(-1, 0);
    a(-.6f, -.2f);
    a(-.4f, -.6f);
    a.setPosition(x, y);
    a.setFill(0, 200, 100);
    a.setGrabbable(false);
    a.setStatic(true);
    a.setName("alien");
    world.add(a);
  }

  public void a(float x, float y) {//shorthand for a.vertex ... scaled
    a.vertex(x*s, y*s);
  }

  public void control(PVector rocketPos) {
    pos.x += r;
    a.setPosition(pos.x, pos.y);//move alien
    timer ++;
    if (timer > value2) {
      timer = 0;
      float a = atan2(rocketPos.y - pos.y,rocketPos.x - pos.x);//angle to rocket
      Bullet b = new Bullet(pos.x, pos.y, a, 5, value * 10000);
      game.obstacles.add(b.getBody());
    }
  }

  public FBody getBody() {
    return a;
  }
}
//class that parses the text file for each round and creates and positions the required items
//all levels must contain a background shape (b) which must have at least 3 vertices as well as a start & target
class Background {

  FPoly b = new FPoly();
  FBox target = new FBox(96, 11);
  FBox start = new FBox(96, 11);
  FBox door = null;
  Bonus [] bonuses = {};
  PVector s, t, wind;
  PVector [] cloudPos = new PVector [3];
  PImage cloud, cloud2, black;
  ArrayList<FBody> obstacles = new ArrayList<FBody>();
  boolean boundless, landscape, controlDoor, doorOpen, noLeft, noRight;
  int bullets = 0;
  String text = "";

  public void reset(String [] levels) {  //initialises a level
    wind  = new PVector(0, 0);
    for (int i = 0; i < cloudPos.length; i ++) {
      cloudPos[i] = new PVector(random(1920), random(540));
    }
    cloud = loadImage("cloud.png");
    cloud2 = loadImage("cloud2.png");
    for (int i = 0; i < levels.length; i ++) {//call parseRow on each row of the txt file
      String [] row = levels[i].split(" ");
      parseRow(row, i);
    }
    //this adds the mandatory FBodies
    b.setStatic(true);
    b.setNoStroke();
    b.setFill(0);
    //b.setFriction(1);
    b.setGrabbable(false);
    b.setName("background");
    world.add(b);
    world.add(start);
    world.add(target);
  }

  public FBody parseRow(String[] row, int i) {
    for (int j = 0; j < row.length; j ++) { //remove empty strings and strings with only spaces in them
      if (row[j].equals("")) {
        for (int k = j; k < row.length-1; k ++) {
          row[k] = row[k+1];
        }
        j --;
        row = shorten(row);
      }
    }
    if (row.length > 0) {
      if (row.length == 1) {
        if (row[0].equals("boundless")) boundless = true;//allow rocket to go off the screen
        else if (row[0].equals("landscape")) {//create large world
          landscape = true;
          boundless = true;
        } else if (row[0].equals("noLeft")) {//disables the left arrow
          noLeft = true;
        } else if (row[0].equals("noRight")) {//disables the right arrow
          noRight = true;
        }
      } else if (row[0].equals("bullets")) {//gives the rocket bullets that can be fired with the spacebar
        bullets = PApplet.parseInt(row[1]);
      } else if (row[0].equals("text")) {//fills the text string which is displayed at the bottom of the screen
        int n = 1;
        while (n != -1) {
          try {
            text = text.concat(row[n] + " ");
            n ++;
          }
          catch(Exception e) {
            n = -1;
          }
        }
      } else {
        if (row.length >= 2) {
          //for all the following (except wind) the first two parameters are the coordinates of the item
          float x = PApplet.parseFloat(trim(row[0]));
          float y = PApplet.parseFloat(trim(row[1]));

          if (i == 0) {//first line of txt file is always start position
            s = new PVector(x*1920, y*1080);
            start.setPosition(x*1920, y*1080);
            start.setFill(200, 0, 0);
            start.setStatic(true);
            start.setFriction(2);
            start.setGrabbable(false);
            start.setName("start");
          } else if (i == 1) {//second line of txt file is always target position
            t = new PVector(x*1920, y*1080);
            target.setPosition(t.x, t.y);
            target.setFill(50, 200, 0);
            target.setStatic(true);
            target.setFriction(2);
            target.setGrabbable(false);
            target.setName("target");
          } else if (row.length == 2) {//adds a vertex to the background polygon
            b.vertex(x*1920, y*1080);
          } else if (row[2].equals("wind")) {//applies a wind to the enviroment (force given by (x, y))
            wind = new PVector(x, y);
          } else if (row[2].equals("time") || row[2].equals("health")
            || row[2].equals("fuel") || row[2].equals("all")) {//adds the bonus
            bonuses = (Bonus[]) append(bonuses, new Bonus(x*1920, y*1080, 24, row[2]));
          }
          //this adds both entrance and exit portals for a teleporter
          else if (row[2].equals("teleporter")) {
            bonuses = (Bonus[]) append(bonuses, new Bonus(x*1920, y*1080, 24, row[2],
              PApplet.parseFloat(row[3])*1920, PApplet.parseFloat(row[4])*1080));
          }
          //adds a black hole / repeller (fourth param is its radius)
          else if (row[2].equals("black") || row[2].equals("repeller")) {
            // black = loadImage("black hole.png");
            bonuses = (Bonus[]) append(bonuses, new Bonus(x*1920, y*1080,
              24, row[2], PApplet.parseFloat(row[3])));
          }
          //adds a wall (stationary narrow obstacle) (fourth param is its radius e.g half its length
          //a negative radius makes it horizontal)
          else if (row[2].equals("wall")) {
            FBody f;
            float d  = 2 * PApplet.parseFloat(row[3]);
            if (d > 0) f = new FBox(10, d);
            else f = new FBox(-d, 10);
            f.setGrabbable(false);
            f.setPosition(x*1920, y*1080);
            f.setStatic(true);
            f.setFill(0);
            f.setName("turnstile");
            world.add(f);
            obstacles.add(f);
            return f;
          }
          //adds a turnstile (fourth param is its radius) (fifth param is speed, setting to zero creates a static obstacle)
          else if (row[2].equals("turnstile")) {
            bonuses = (Bonus[]) append(bonuses, new Turnstile(x*1920, y*1080, PApplet.parseFloat(row[3]), PApplet.parseFloat(row[4])));
            return bonuses[bonuses.length-1].getBody();
          }
          //adds a slider (fourth param is its radius) (fifth param is speed) (sixth is start position (range from -1 to 1) or 2
          else if (row[2].equals("slider")) {
            bonuses = (Bonus[]) append(bonuses, new Turnstile(x*1920, y*1080,
              PApplet.parseFloat(row[3]), PApplet.parseFloat(row[4]), PApplet.parseFloat(row[5])));
            return bonuses[bonuses.length-1].getBody();
          }
          //adds a circular non-static obstacle (fourth param is its radius) (fifth is optional for density)
          else if (row[2].equals("blob")) {
            FBody f = new FCircle(PApplet.parseFloat(row[3]));
            f.setFill(100, 100, 0);
            try {
              f.setDensity(PApplet.parseFloat(row[4]));
            }
            catch(Exception e) {
              f.setDensity(0.01f);
            }
            f.setGrabbable(false);
            f.setPosition(x*1920, y*1080);
            world.add(f);
            obstacles.add(f);
            f.setName("box");
            return f;
          }
          //adds a rectangular non-static obstacle (fourth and fifth params are dimensions)
          //(sixth is optional for density)
          else if (row[2].equals("box")) {
            FBody f = new FBox(PApplet.parseFloat(row[3]), PApplet.parseFloat(row[4]));
            f.setFill(0, 100, 100);
            try {
              f.setDensity(PApplet.parseFloat(row[5]));
            }
            catch(Exception e) {
              f.setDensity(0.01f);
            }
            f.setGrabbable(false);
            f.setPosition(x*1920, y*1080);
            f.setName("blob");
            world.add(f);
            obstacles.add(f);
            return f;
          }
          //creates a chain between to objects (half-baked implementation here, do fix it :) )
          else if (row[2].equals("chain")) {
            int len;
            FBody[] steps = new FBody [100];
            float xTo, yTo;
            if (row.length < 11) {
              String [] a = {row[0], row[1], row[3], row[4]};
              String [] b = {row[5], row[6], row[7], row[8]};
              len = PApplet.parseInt(row[9]);
              steps[0] = parseRow(a, 2);
              steps[len-1] = parseRow(b, 2);
              yTo = PApplet.parseFloat(row[6])*1080;
              xTo = PApplet.parseFloat(row[5])*1920;
            } else {
              String [] a = {row[0], row[1], row[3], row[4], row[5]};
              String [] b = {row[6], row[7], row[8], row[9], row[10]};
              len = PApplet.parseInt(row[11]);
              steps[0] = parseRow(a, 2);
              steps[len-1] = parseRow(b, 2);
              yTo = PApplet.parseFloat(row[7])*1080;
              xTo = PApplet.parseFloat(row[6])*1920;
            }
            for (int j = 1; j < len-1; j ++) {
              steps[j] = new FCircle(5.0f);
              steps[j].setFill(0);
              steps[j].setGrabbable(false);
              steps[j].setPosition(map(j, 0, len, x*1920, xTo), map(j, 0, len, yTo, y*1080));
              steps[j].setName("chain");
              world.add(steps[j]);
              obstacles.add(steps[j]);
            }
            for (int j = 1; j < len; j ++) {
              FDistanceJoint joint = new FDistanceJoint(steps[j-1], steps[j]);
              joint.setAnchor1(0, 0);
              joint.setAnchor2(0, 0);
              joint.setFill(128);
              if (i != 1 && i != len-1) joint.setLength(5);
              world.add(joint);
            }
          }
          //adds a button to the world which will open and close a door (nearly as bad as chain ...)
          //(fourth and fifth params are coordinates, sixth and seventh are dimensions)
          else if (row[2].equals("button")) {
            FBox f = new FBox(96, 10);
            f.setFill(255, 100, 0);
            f.setStatic(true);
            world.add(f);
            f.setFriction(2);
            f.setGrabbable(false);
            f.setName("button");
            f.setPosition(x*1920, y*1080);
            door = new FBox(PApplet.parseFloat(row[5])*1920, PApplet.parseFloat(row[6])*1080);
            door.setName("door");
            door.setFill(255, 255, 0, 100);
            door.setNoStroke();
            door.setGrabbable(false);
            door.setStatic(true);
            world.add(door);
            door.setPosition(PApplet.parseFloat(row[3])*1920, PApplet.parseFloat(row[4])*1080);
            controlDoor = true;
          } else if (row[2].equals("alien")) {
            bonuses = (Bonus[]) append(bonuses, new Alien(x*1920, y*1080,
              PApplet.parseFloat(row[3]), PApplet.parseFloat(row[4]), PApplet.parseFloat(row[5])));
            return bonuses[bonuses.length-1].getBody();
          }
        }
      }
    }
    return null;
  }

  public void controlDoor(boolean open) {
    if (open && !doorOpen) {
      doorOpen = true;
      world.remove(door);
    } else if (!open && doorOpen) {
      doorOpen = false;
      world.add(door);
    }
  }

  public void controlBonuses(PVector rocketPos) {
    for (Bonus b : bonuses) {
      b.control(rocketPos);
    }
  }

  public void control(PVector rocketPos) {//controls the clouds
    for (int i = 0; i < cloudPos.length; i ++) {
      image(cloud2, cloudPos[i].x, cloudPos[i].y, 100, 100);
      cloudPos[i].x += .5f + game.ship.wind.x/200;
      if (boundless) {
        if (cloudPos[i].x > 3940) cloudPos[i].x = -2020;
        else if (cloudPos[i].x < -2120) cloudPos[i].x = 3940;
      } else {
        if (cloudPos[i].x > 1920 + 100) cloudPos[i].x = -100;
        else if (cloudPos[i].x < -200) cloudPos[i].x = 1920;
      }
    }
  }
}
//class that displays and controls the bonuses (and some obstacles)

class Bonus {

  PVector pos;
  float r, value, value2;//the values have different meanings depending on the type
  String type;

  Bonus() {
  }

  Bonus(float x, float y, float r, String type) {
    pos = new PVector(x, y);
    this.r = r;
    this.type = type;
  }

  Bonus(float x, float y, float r, String type, float value) {
    pos = new PVector(x, y);
    this.r = r;
    this.type = type;
    this.value = value;
  }

  Bonus(float x, float y, float r, String type, float value, float value2) {
    pos = new PVector(x, y);
    this.r = r;
    this.type = type;
    this.value = value;
    this.value2 = value2;
  }

  public void control(PVector rocketPos) {
    push();
    translate(pos.x, pos.y);
    stroke(0);
    strokeWeight(4);
    if (type.equals("black") || type.equals("repeller") ) {//draws succsessive transparent circles
      noStroke();
      if (value > 500) {
        for (float i = value; i > r; i -= 200) {
          if (type.equals("black")) fill(0, map(i, r, value, 0, 150));
          else fill(255, 0, 0, map(i, r, value, 0, 150));
          circle(0, 0, i*2);
        }
      } else {
        for (float i = value; i > r; i -= 100) {
          if (type.equals("black")) fill(0, map(i, r, value, 0, 100));
          else fill(255, 0, 0, map(i, r, value, 0, 100));
          circle(0, 0, i*2);
        }
      }
    } else if (type.equals("teleporter")) {
      fill(190, 190, 80);
      circle(0, 0, r*2);
      fill(150, 150, 0);
      circle(value-pos.x, value2-pos.y, r*2);
    } else {
      fill(150, 0, 255);
      circle(0, 0, r*2);
      if (type.equals("time")) { //clock symbol
        clock();
      } else if (type.equals("health")) { //draws a heart
        heart();
      } else if (type.equals("fuel")) {
        flame();
      } else if (type.equals("all")) {
        all();
      }
    }
    pop();
    //this is bad... applies a force to the rocket and then does the same for all the other obstacles
    if (type.equals("black") || type.equals("repeller")) {
      float mult = 500*sq(value);
      PVector toRocket = new PVector(rocketPos.x - pos.x, rocketPos.y - pos.y);
      float theta = PI+toRocket.heading();
      float mag = toRocket.mag();
      if (mag < r*2) {
        game.info.destroyed = true;
        game.info.health = -1;
        engine.playing = false;
        engine.gameOver = true;
      }
      mag = mult/sq(mag);
      if (type.equals("black")) game.ship.rocket.addForce(mag*cos(theta), mag*sin(theta));
      else game.ship.rocket.addForce(-mag*cos(theta), -mag*sin(theta));
      if (game.obstacles.size() > 0) {
        for (int i = 0; i < game.obstacles.size(); i ++) {
          FBody f = game.obstacles.get(i);
          PVector toF = new PVector(f.getX() - pos.x, f.getY() - pos.y);
          float thetaF = PI+toF.heading();
          float magF = toF.mag();
          magF = mult/sq(magF);
          if (type.equals("black")) f.addForce(magF*cos(thetaF), magF*sin(thetaF));
          else f.addForce(-magF*cos(thetaF), -magF*sin(thetaF));
        }
      }
    }
    //if center of rocket goes through one of these bonuses...
    if (pos.copy().dist(rocketPos) < r) {
      if (type.equals("all")) {
        game.info.time = 100;
        game.info.health = 100;
        game.info.hit = false;
        game.info.fuel = 100;
      }
      if (type.equals("time")) game.info.time = 100;
      else  if (type.equals("health")) {
        game.info.health = 100;
        game.info.hit = false;
      } else  if (type.equals("fuel")) game.info.fuel = 100;
      else  if (type.equals("teleporter")) game.ship.rocket.setPosition(value, value2);
    }
  }

  public void heart() {
    noStroke();
    fill(255, 0, 0);
    circle(.3f*r, -.3f*r, .6f*r);
    circle(-.3f*r, -.3f*r, .6f*r);
    rotate(-PI/4);
    rectMode(CENTER);
    square(0, 0, .6f*r);
  }

  public void clock() {
    line(0, 0, .6f*r, -.6f*r);
    line(0, 0, -.4f*r, -.4f*r);
  }

  public void flame() {
    image(game.flame, 0, 0, 35, 35);
  }

  public void all() {
    translate(-10, 5);
    heart();
    rotate(PI/4);
    translate(20, 0);
    flame();
    stroke(0);
    strokeWeight(4);
    translate(-10, -5);
    clock();
  }

  public FBody getBody() { //so that extended classes can use this method
    return null ;
  }
}
class Bullet extends Bonus {

  FCircle c;
  float v;

  Bullet(float x, float y, float a, float r, float value) {
    //this.v = v;
    super(x, y, r, "bullet", value);
    c = new FCircle(r*2);
    c.setFill(0xFF7C9AC9);
    c.setPosition(x + 50*cos(a), y + 50*sin(a));
    c.setBullet(true);
    world.add(c);
    c.setName("bullet");
    c.addForce(value*cos(a), value*sin(a));
  }

  public void control(PVector rocketPos) {
   // float a = game.ship.rocket.getRotation()-PI/2;
    //c.addForce(value*cos(a), value*sin(a));
    //c.setVelocity(
    //c.setPosition
  }

  public FBody getBody() {
    return c;
  }
}
//creates the buttons in the menu

class Button {
  float x;
  float y;
  float w;
  float h;
  String s;
  int c;

  Button(float x1, float y1, float w1, float h1, String s1, int c1) {
    x = x1-w1/2;
    y = y1-h1/2;
    w = w1;
    h = h1;
    s = s1;
    c = c1;
  }

  public void display() {
    //pushStyle();
    stroke(c);
    strokeWeight(h);
    line(x+h/2, y+h/2, x+w-h/2, y+h/2);
    strokeWeight(1);
    stroke(0);
    fill(0);
    if (s.length() > 2) {
      if (h >= 40) {
        textSize(25);
        textAlign(CENTER);
        textLeading(20);
      } else {
        textSize(20);
        textAlign(CENTER);
        textLeading(18);
      }
      if (c != color(70, 200, 170))text(s, x, y+h/4, w, h);
      else text(s, x, y+h/10, w, h);//'another'
    }
    //popStyle();
  }

  public boolean pressed() {
    if (mouseX/scale > x && mouseX/scale < x + w && mouseY/scale > y && mouseY/scale < y + h) return true;
    else return false;
  }
}
//class that controls all the menues and stores stats.

class Engine {

  boolean playing, gameOver, displayScoresheet, displayLevels, displayInfo, pause;
  int level = 1;
  int maxLevel = 50;
  String filePath = "C:rocket_scoresheet.txt";
  PImage rocket_pic = loadImage("rocket_pic.png");
  Button [] levels = {};
  Button playGame, nextLevel, info, scoresheet;

  Engine() {//create buttons
    float bw = 200;
    float bh = 100;
    playGame = new Button(320, 900, bw, bh, "Play Game", color(150, 255, 0));
    nextLevel = new Button(640, 900, bw, bh, "Next Level", color(0, 255, 0));
    info = new Button(960, 900, bw, bh, "Info", color(100, 255, 255));
    scoresheet = new Button(1280, 900, bw, bh, "Scoresheet", color(150, 0, 255));
    for (int i = 0; i < 50; i ++) {
      levels = (Button[]) append(levels, new Button(380 + (i%5)*320,
        80 + 77*floor(i/5), bh*3, 65, nf(i+1), color(50, 150, 50)));
    }
    myFont = createFont("Comic Sans MS", 70);
    textFont(myFont);
  }

  public void control() {
    if (!pause) {
      background(80, 120, 200);
      if (displayScoresheet) {
        scoresheet.display();
        displayScoresheet();
      } else if (displayInfo) {
        info.display();
        displayInfo();
      } else {
        if (playing) {
          game.control();
        } else {
          textSize(500);
          fill(220, 100, 0, 150);
          text("Rocket !", 1920/2, 400);
          playGame.display();
          if (level < maxLevel) nextLevel.display();
          info.display();
          scoresheet.display();
          if (gameOver) resetScores();
          cursor();
          gameOver = false;
          try {
            game.info.displayScore();
          }
          catch (Exception e) {
          }
        }
      }
    }
  }

  public void displayInfo() {
    textSize(30);
    imageMode(CORNER);
    text("Welcome to rocket!\nCan you land your rocket upright on the green destination pad each level? Better still, can you get 10 stars for each level?\n"
      + "Each of the 50 levels poses new challenges for your Rocket to navigate.\n "
      + "Be careful not to fly out of bounds, be shot by aliens, fly into any closed beige doors, or to fall into any black holes along the way.\n"
      + "Beige doors are opened while an object is on an orange pad.\n"
      + "In addition your rocket has limited time, fuel, and damage resistance, however these can be reset by flying through their respective purple power-ups. "
      + "Flying through the health power-up will also reset the hit star.\n"
      + "Controls and Shortcuts: use the arrow keys or AWD to control the spaceship" 
      + "(pressing A, D or side arrow keys will result in the rocket being propelled forward as well as rotated), press p to pause/unpause the game, m to go to menu, "
      + "shift to play next level, space to fire bullets (in some of the later levels), and r to restart the level.\n"
      + "\n"
      + "Good luck, hope you enjoy the game :)"
      , 0, 70, 1920, 1000);
    image(rocket_pic, 1250, 700, 570, 509);
  }

  public void displayScoresheet() {
    for (Button b : levels) b.display();
    try {
      String [] scores = loadStrings(filePath);
      textSize(25);
      text("Click on any of the green buttons to play any level.", 400,900);
      for (int i = 1; i < scores.length; i ++) {
        fill(0);
        text("level " + i + ": " + scores[i] + "/10", ((i-1)%5)*320 + 330, (1+floor((i-1)/5.0f))*77);
        fill(255, 255, 0);
        noStroke();
        for (int j = 0; j < 10; j ++) {
          if (j >= PApplet.parseInt(scores[i])) fill(120);
          displayStar((((i-1)%5) + 1)*320 + PApplet.parseInt(j*25 - 50), (1+floor((i-1)/5.0f))*77 + 20, 15);
        }
      }
    }
    catch(Exception e) {//file problem
      println(e);
    }
  }

  public void resetScores() {
    int n = 0;
    try {
      n = game.info.displayScore();// score from last level played
    }
    catch(Exception e) {
    }
    try {
      String [] scores = loadStrings(filePath);
      while (scores.length <= level) {
        scores = append(scores, "0");
      }
      if (PApplet.parseInt(scores[level]) < n) {//if last score was better than your best score for that level, update the score
        scores[level] = str(n);
        saveStrings(filePath, scores);
      }
    }
    catch(Exception e) {//if no file was found, create a new one and populate with zeroes until it reaches the level you just played
      String [] scores = new String [maxLevel + 1];
      scores[0] = "";
      for (int i = 0; i <= maxLevel; i ++) {
        scores[i] = "0";
      }
      if (PApplet.parseInt(scores[level]) < n) {//if last score was better than your best score for that level, update the score
        scores[level] = str(n);
        saveStrings(filePath, scores);
      }
      println(e);
    }
  }

  public void startGame() {
    playing =  true;
    game = new Game();
    playGame.s = "Retry Level";
    gameOver = false;
    noCursor();
  }

  public void mousePressed() {
    if (!playing) {
      if (displayScoresheet) {
        for (Button b : levels) {
          if (b.pressed()) { //try to run the selected level
            level = PApplet.parseInt(b.s);
            try {
              startGame();
              displayScoresheet = false;
              scoresheet.s = "Scoresheet";
            }
            catch(Exception e) {
              println(e);
              playing = false;
              level = 1;
            }
          }
        }
      }

      if (scoresheet.pressed()) { //toggle visability of scoresheet
        if (displayScoresheet) scoresheet.s = "Scoresheet";
        else  scoresheet.s = "Back";
        displayScoresheet = !displayScoresheet;
      }
      if (info.pressed()) { //toggle visability of info
        if (displayInfo) info.s = "Info";
        else  info.s = "Back";
        displayInfo = !displayInfo;
      }
      if (!displayScoresheet && !displayLevels && playGame.pressed()) startGame(); //run same level as before or ...
      // ... level 1 if no level has yet been played
      if (!displayScoresheet && !displayLevels && playing == false && nextLevel.pressed() && level < maxLevel) {
        //run next level after the one that was last played or level 2 if no level has yet been played
        nextLevel();
      }
    }
  }

  public void keyPressed() { //various shortcuts
    if (playing) game.keyPressed();
    else if (keyCode == ENTER) startGame();
    else if (keyCode == SHIFT) nextLevel();
    if (key == 'm' || key == 'M') {//go to menu
      pause = false;
      gameOver = false;
      displayScoresheet = false;
      displayLevels = false;
      displayInfo = false;
      scoresheet.s = "Scoresheet";
      info.s = "Info";
      if (playing) {
        playing = false;
        game.info.aborted = true;
        game.info.health = -1;
      }
    } else if (key == 'r' || key == 'R') { //restart level
      pause = false;
      startGame();
    } else if (playing && !gameOver && (key == 'p' || key == 'P')) { //pause game
      pause = ! pause;
    }
  }

  public void keyReleased() {
    if (playing) game.keyReleased();
  }

  public void nextLevel() { //trys to run a new level if there is one and if the new level parses correctly
    level ++;
    try {
      startGame();
    }
    catch(Exception e) {//this should not run unless nextlevel is clicked after level 50 or if files are messed with
      level --;
      try {
        startGame();
      }
      catch(Exception e2) {//even less likely to run
        println(e2);
      }
    }
  }
}
class Flame{
 
  float x, y, size, noise, angle;
  
  Flame(float x, float y, float size, float angle, float noise){
    this.x = x;
    this.y = y;
    this.size = size;
    this.angle = angle;
    this.noise = noise;
  }
  
  public void control(){
    fill(150 + noise(noise+300)*100, 100 + noise(noise+200)*100, 0, size*10);
    circle(x,y,(1+noise(noise+1000))*10);
    size -= .1f;
    noise += .05f;
    x += 3*(noise(noise)-.5f) + cos(angle)*1.5f;
    y += 3*(noise(noise+100)) - 1 + sin(angle)*1.5f;
  }
}
//class that controls the actual game

class Game {

  Background background;
  Info info = new Info();
  Ship ship;
  boolean up, left, right, door, knocked;
  PVector v = new PVector(0, 0);
  ArrayList<FBody> obstacles;
  PImage flame, blackHole;
  int bullets = 0;

  Game() {
    smooth();
    textSize(30);
    textAlign(CENTER, CENTER);
    imageMode(CENTER);
    flame = loadImage("flame.png");
    obstacles = new ArrayList<FBody>();
    String[] levels = loadStrings("level" + engine.level + ".txt");
    world = new FWorld(-1920, -1920, 3840, 3840);
    world.setGravity(0, 200);
    ship = new Ship();
    background = new Background();
    background.reset(levels);
    bullets = background.bullets;
    ship.rocket.setPosition(background.s.x, background.s.y - 48);
    ship.wind  = background.wind;
    for (int i = 0; i < background.obstacles.size(); i ++) {
      obstacles.add(background.obstacles.get(i));
    }
  }

  public void control() {
    pushMatrix();
    if (background.landscape) {//position the screen
      float tx = 1920/2 - ship.rocket.getX();
      float ty = 1080/2 - ship.rocket.getY();
      tx = constrain(tx, -1920*.98f, 1920*.98f);
      ty = constrain(ty, -1080*.98f, 1080*.98f);
      translate(tx, ty);
    }
    background.control(ship.getPosition()); //clouds
    if(engine.level == 49){ //haha I'll let you decide if this is cheating
      fill(0);
      rect(0,.8f*height, width, .8f*height);
      rect(0,.2f*height,.2f*width, .6f*height);
    }
    world.step();
    world.draw();
    ship.control();
    background.controlBonuses(ship.getPosition());
    if (ship.landed(background.t)) {
      engine.playing = false;
      engine.gameOver = true;
    }
    popMatrix();
    fill(255, 150, 255);
    text(background.text, 768, 972);
    if (background.controlDoor) background.controlDoor(door);
    info.control();
  }

  public void fail() {
    game.info.health = -1;
    engine.playing = false;
    engine.gameOver = true;
  }

  public void contactStarted(FContact c) {
    v = ship.getVelocity();
    if (c.contains("rocket", "door")) {
      info.destroyed = true;
      fail();
    }
    if (c.contains(ship.rocket) &&
      (!(c.contains(background.start) || c.contains(background.target)))) {
      info.hit = true;
      knocked = true;
    }
    String n1 = c.getBody1().getName();
    String n2 = c.getBody2().getName();
    if (c.contains("bullet")) {
      if (!n1.equals("background") && !n1.equals("door") && !n1.equals("target")
        && !n1.equals("turnstile") && !n1.equals("alien")) {
        world.remove(c.getBody1());
      }
      if (!n2.equals("background") && !n2.equals("door") && !n2.equals("target")
        && !n2.equals("turnstile") && !n2.equals("alien")) {
        world.remove(c.getBody2());
      }
      if (c.contains("rocket")) {
        info.shot = true;
        fail();
      }
    }
  }

  public void contactPersisted(FContact c) {
    if (c.contains("button") && !c.contains("background")) {
      door = true;
    }
  }

  public void contactEnded(FContact c) {
    if (v.x != 0 && v.y != 0 && knocked) {
      PVector z = v.copy().sub(ship.getVelocity());
      info.health -= z.mag()/5;
      knocked = false;
    }
    if (c.contains("button")) door = false;
  }

  public void keyPressed() {
    if (keyCode == UP || key == 'w' || key == 'W') up = true;
    else if ((keyCode == LEFT || key == 'a' || key == 'A') && !background.noLeft) left = true;
    else if ((keyCode == RIGHT || key == 'd' || key == 'D') && !background.noRight) right = true;
    if (key == ' ' && bullets > 0) {//shoot!
      Bullet b = new Bullet(game.ship.rocket.getX(), game.ship.rocket.getY(),
        ship.rocket.getRotation() - PI/2, 5, 10000 + ship.getVelocity().copy().mag()*20);
      obstacles.add(b.getBody());
      bullets --;
    }
  }

  public void keyReleased() {
    if (keyCode == UP || key == 'w' || key == 'W') up = false;
    else if (keyCode == LEFT || key == 'a' || key == 'A') left = false;
    else if (keyCode == RIGHT || key == 'd' || key == 'D') right = false;
  }
}
//class that controls the info shown in the bottom-right corner of the screen when playing

class Info {

  float fuel;
  float health;
  float time;
  boolean hit, outOfBounds, destroyed, aborted, shot;

  Info() {
    fuel = 100;
    health = 100;
    time = 100;
    hit = false;
  }

  public void control() {
    time -= .07f;
    if (game.up) fuel -= .2f;
    if (game.left) fuel -= .05f;
    if (game.right) fuel -= .05f;
    fill(128);
    text("Hit", 1920*.97f, 1080*.91f);
    if (!hit) {
      fill(255, 255, 0);
      displayStar(PApplet.parseInt(1920*.97f), PApplet.parseInt(1080*.95f), 20);
    }
    if (game.bullets > 0) {
      fill(150, 0, 0);
      text(game.bullets + " bullets", 1536, 1040);
    }
    fill(128);
    text("Level " + engine.level, 70, 1050);
    displaySlider(1536, 910, 288, fuel, "Fuel");
    displaySlider(1536, 960, 288, health, "Health");
    displaySlider(1536, 1010, 288, time, "Time");
    if (lost()) {
      game.fail();
    }
  }

  public boolean lost() {
    if (fuel < 0 || health < 0 || time < 0) return true;
    return false;
  }

  public int displayScore() {
    int n = 0;
    textSize(40);
    if (lost()) {
      fill(255, 0, 0);
      text("Level " + engine.level + " failed!", 960, 532);
      String cause = "?";
      if (destroyed) cause = "Your rocket was destroyed.";
      else if (aborted) cause = "You aborted this level.";
      else if (shot) cause = "Your rocket was shot.";
      else if (outOfBounds) cause = "Your rocket flew out of bounds.";
      else if (fuel < 0) cause = "Your rocket ran out of fuel.";
      else if (time < 0) cause = "Your rocket ran out of time.";
      else if (health < 0) cause = "Your rocket has become irrepairably damaged.";
      text(cause, 960, 640);
    } else {
      n = countScore();
      fill(50, 255, 50);
      text("Level " + engine.level + "  Completed!", 960, 532);
      fill(0);
      text("Score = " + n, 960, 586);
      fill(255, 255, 0);
      noStroke();
      for (int i = 0; i < 10; i ++) {
        if (i >= n) fill(120);
        displayStar(PApplet.parseInt(640 + i*71), 640, 32);
      }
    }
    return n;
  }

  public int countScore() {
    return stars(fuel) + stars(health) + stars(time) + stars(hit);
  }

  public int stars(float in) {
    if (in >= 40) return 3;
    if (in >= 25) return 2;
    if (in >= 10) return 1;
    return 0;
  }

  public int stars(boolean b) {
    if (b) return 0;
    return 1;
  }

  public void displaySlider(int x, int y, int w, float value, String name) {
    stroke(0);
    fill(128);
    rect(x, y, w, 10);
    text(name, x - 60, y - 15);
    noStroke();
    if (value > 0) {
      fill(50, 200, 0);
      rect(x, y, value*w/100, 10);
    }
    fill(220, 220, 0);
    if (value >= 10) {
      displayStar(x + w/10, y - 10, 20);
    }
    if (value >= 25) {
      displayStar(x + w/4, y - 10, 20);
    }
    if (value >= 40) {
      displayStar(x + w*4/10, y - 10, 20);
    }
  }
}
//class that controls the spaceship, the object is called 'ship' but the FBody is called 'rocket'

class Ship {
  FPoly rocket;
  float s = 1920/45;
  PShape ship;
  ArrayList<Flame> flames = new ArrayList<Flame>();
  PVector wind;

  Ship() {
    rocket = new FPoly();
    v(0, -1);  //define the vertices of the rocket, by default it points up
    v(.2f, -.7f);
    v(.3f, -.3f);
    v(.3f, .4f);
    v(.43f, .47f);
    v(.5f, .7f);
    v(.5f, 1);
    v(.2f, .7f);
    v(-.2f, .7f);
    v(-.5f, 1);
    v(-.5f, .7f);
    v(-.43f, .47f);
    v(-.3f, .4f);
    v(-.3f, -.3f);
    v(-.2f, -.7f);
    rocket.setFill(220, 100, 0);
    rocket.setNoStroke();
    rocket.setGrabbable(false);
    rocket.setDensity(1);
    rocket.setBullet(true);
    rocket.setName("rocket");
    world.add(rocket);
    wind = new PVector(0, 0);
  }

  public PVector getVelocity() {
    PVector out = new PVector(rocket.getVelocityX(), rocket.getVelocityY());
    return out;
  }

  public PVector getPosition() {
    PVector out = new PVector(rocket.getX(), rocket.getY());
    return out;
  }

  public void v(float x, float y) {//shorthand for rocket.vertex ... scaled
    rocket.vertex(x*s, y*s);
  }

  public void display() {
    push();
    translate(rocket.getX(), rocket.getY());
    rotate(rocket.getRotation());
    fill(0);
    for (int i = 0; i < 4; i ++) {//rocket windows
      square(-.05f*s, (i/3.0f - .5f)* s, .1f*s);
    }
    if (game.up) { //lots of flames
      for (int i = 0; i < 2; i ++) {
        flames.add(new Flame(rocket.getX() + s*random(.6f,.8f)*cos(rocket.getRotation()+PI/2),
          rocket.getY() + s*random(.6f,.8f)*sin(rocket.getRotation()+PI/2),
          random(2, 4) + random(2, 4) + random(2, 4) + random(2, 4) + random(2, 4),
          rocket.getRotation()+PI/2, random(100000)));
      }
    }
    if (game.left) { //flames coming out bottom-right
      for (int i = 0; i < 3; i ++) {
        flames.add(new Flame(rocket.getX() + s*random(.4f,.6f)*cos(rocket.getRotation()+PI/4),
          rocket.getY() + s*random(.4f,.6f)*sin(rocket.getRotation()+PI/4),
          random(3, 5), rocket.getRotation()+PI/4, random(100000)));
      }
    }
    if (game.right) {  //flames coming out bottom-left
      for (int i = 0; i < 3; i ++) {
        flames.add(new Flame(rocket.getX() + s*random(.4f,.6f)*cos(rocket.getRotation()+3*PI/4),
          rocket.getY() + s*random(.4f,.6f)*sin(rocket.getRotation()+3*PI/4),
          random(3, 5), rocket.getRotation()+3*PI/4, random(100000)));
      }
    }
    pop();
    for (int i = 0; i < flames.size(); i ++) { //remove flames that have disappeared
      flames.get(i).control();
      if (flames.get(i).size <= 0) flames.remove(i);
    }
  }

  public void control() {//applies forces to the rocket
    float a = rocket.getRotation() + PI/2;
    rocket.addForce(wind.x, wind.y);
    if (((rocket.getX() < 0 || rocket.getY() < 0 || rocket.getX() > 1920 || rocket.getY() > 1080)
      && !game.background.boundless) ||
      (rocket.getX() < -1920*.98f || rocket.getY() < -1080*.98f
      || rocket.getX() > 1920*1.98f || rocket.getY() > 1080*1.98f)) {
      game.info.outOfBounds = true;
      game.fail();
    }
    if (keyPressed) {
      if (game.up) rocket.addForce(-3000*cos(a), -3000*sin(a));
      if (game.right) {
        rocket.addTorque(5);
        rocket.addForce(-500*cos(a), -500*sin(a));
      }
      if (game.left) {
        rocket.addTorque(-5);
        rocket.addForce(-500*cos(a), -500*sin(a));
      }
    }
    display();
  }

  public boolean landed(PVector t) {//true if rocket has landed correctly on landing pad
    if (dist(t.x, t.y, rocket.getX(), rocket.getY()) < s+20 && same(rocket.getRotation(), 0)
      && abs(rocket.getVelocityX()) < .01f && abs(rocket.getVelocityY()) < .01f) return true;
    return false;
  }

  public boolean same(float a, float b) {//true if the angles are within PI/24 of each other
    float ab = abs(((a+TAU) % TAU) - ((b+TAU) % TAU));
    if (ab < PI/24 || ab > TAU - PI/24) return true;
    return false;
  }
}
//this class also controls the sliders

class Turnstile extends Bonus {

  FBox t;
  float theta = 0;
  boolean slider;

  Turnstile(float x, float y, float r, float value) {
    super(x, y, r, "turnstile", value);
    init();
  }

  Turnstile(float x, float y, float r, float value, float value2) {
    super(x, y, r, "turnstile", value, value2 * PI);
    slider = true;
    init();
  }

  public void init() { //initialises either a slider or a turnstile. A negative radius will make the object
    // start 90 deg out of order for turnstile and will cause slider to move horizontally
    if (r > 0)t = new FBox(10, abs(r)*2);
    else t = new FBox(abs(r)*2, 10);
    t.setPosition(pos.x, pos.y);
    t.setFill(0);
    t.setFriction(0);
    t.setGrabbable(false);
    t.setStatic(true);
    t.setName("turnstile");
    world.add(t);
  }

  public void control(PVector rocketPos) {
    if (slider) {
      if (r > 0) {
        t.setPosition(pos.x, pos.y + cos(value2)*r);
      } else {
        t.setPosition(pos.x + cos(value2)*r, pos.y);
      }
      value2 += value;
    } else {//turnstile
      t.setRotation(theta);
      if (value != 0) theta += value;
    }
  }

  public FBody getBody() {
    return t;
  }
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "rocket2" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
